@startuml
title Login

actor user
participant UI_LOGIN
participant UI_REGISTER
participant UI_PROJECTS
participant Facade << (C,#FFFFFF) singleton >>
participant UserManager << (C,#FFFFFF) singleton >>
participant DB << (C,#FFFFFF) singleton >>
participant SQL_RESULT

activate user
    user -> UI_LOGIN: introduce email, password
    activate UI_LOGIN
        UI_LOGIN -> Facade: exists(mail, pass): bool
        activate Facade
            Facade -> UserManager: exists(mail, pass): bool
            activate UserManager
                UserManager -> DB: execSQL(SQL_USER_EXISTS)
                activate DB
                    DB -> SQL_RESULT: new()
                deactivate DB
                activate SQL_RESULT
                UserManager -> SQL_RESULT: next()
                UserManager -> SQL_RESULT: close()
                deactivate SQL_RESULT
                destroy SQL_RESULT
                UserManager --> Facade: bool
            deactivate UserManager
            Facade --> UI_LOGIN: bool
        deactivate Facade
    deactivate UI_LOGIN
    ' mostrar los demas
deactivate user
@enduml