@startuml

' CASO DE USO: login

title Register

actor user
participant UI_LOGIN
participant UI_REGISTER
participant UI_PROJECTS
participant Facade << (C,#FFFFFF) singleton >>
participant UserManager << (C,#FFFFFF) singleton >>
participant DB << (C,#FFFFFF) singleton >>
participant SQL_RESULT

activate user
    user -> UI_LOGIN: click en registrarse
    activate UI_LOGIN
        UI_LOGIN -> UI_REGISTER: new()
        activate UI_REGISTER
            UI_REGISTER -> Facade: createUser(mail, name, pass): bool
            activate Facade
                Facade -> UserManager: createUser(mail, name, pass): bool
                activate UserManager
                    UserManager -> DB: execSQL(SELECT_EMAIL)
                    activate DB
                        DB -> SQL_RESULT: new()
                    deactivate DB
                    activate SQL_RESULT
                        UserManager -> SQL_RESULT: next()
                        UserManager -> SQL_RESULT: close()
                        deactivate SQL_RESULT
                        destroy SQL_RESULT
                        alt user exists
                            UserManager --> Facade: false
                            Facade --> UI_REGISTER: false
                            UI_REGISTER -> UI_REGISTER: show_toast("ya existe")
                            activate UI_REGISTER
                            deactivate UI_REGISTER
                        else user doesn't exist
                            UserManager -> DB: execSQL(SQL_CREATE_USER)
                            activate DB
                            deactivate DB
                            UserManager --> Facade: true
                deactivate UserManager
                            Facade --> UI_REGISTER: true
            deactivate Facade
                            UI_REGISTER -> UI_REGISTER: finish()
                            UI_REGISTER -> UI_PROJECTS: new(email)
                            activate UI_PROJECTS
                            deactivate UI_PROJECTS
                        end
        deactivate UI_REGISTER
        destroy UI_REGISTER
    deactivate UI_LOGIN
deactivate user

@enduml